dep: updates wazero to v1.0.0-pre.1
vmware-samples/webassembly-browser-apps pull request #4
Opened 2022-09-01 02:48 UTC by mathetake

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

2022-09-01 02:49 UTC, mathetake commented on pi-zero-ssr/handler/main.go
>  package main
This file has been formatted with `gofmt` which is the official standard that everyone uses in Go projects.

2022-09-01 21:47 UTC, ereslibre approved these changes
Thanks @mathetake!

Approving, can be merged when the contributor license agreement is confirmed.

2022-09-01 21:48 UTC, ereslibre commented on pi-zero-ssr/handler/go.mod
> +require github.com/tetratelabs/wazero v1.0.0-pre.1
🎉

2022-09-07 09:58 UTC, Angelmmiguel requested changes
Hello @mathetake !

Thank you very much for the pull request. Happy to see Wazero is close to v1.0.0! I already tested the new version on the Raspberry Pi Zero W and it works perfectly.

Before merging this PR, I found your editor modified all the spaces in the `main.go` file. To keep the MR only with required changes, please could you revert those space changes and keep only the one in the `import` block? (I think that's the only required)

We will lint these files and add a GitHub Action in a separate MR.

Thank you!

2022-09-07 12:11 UTC, merged